name: Cyloam Cycling Club
favicon: null
layout_spectrum: 0.47882490372285247
typography_spectrum: 0.39961026841774583
title: Cyloam Cycling Club
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c2c2a'
    - '#a79c93'
    - '#feb55c'
    - '#686a61'
  brandStrength: 0.8686817097477615
  lightness: 0.18680473254062235
  saturation: 0.20865255687385798
  rhythmicContrast: 0.9871240528300405
purpose: []
